@startuml FilterAdoption
' Global param
title  Filter Adoption
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "_:AdoptionPage_" as  Page <<view>>
participant "_:AdoptionService_" as Service
participant "_:_Adoption_" as Model <<model>>
participant "_:DioInstance_" as Dio


' Sequence diagram
User -> Page: build(context)

end

@enduml