@startuml Delete User
' Global param
title Delete User
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor Admin
participant "__:AdminUsersCard__" as Card <<view>>
participant "__:AdminService__" as Service
participant "__:Admin__" as Model <<model>>
participant "__:DioInstance__" as Dio


' Sequence diagram
Admin -> Card : build(context)
Admin <-- Card: return confirmation pop up
alt confirm delete account
Admin -> Card: confirm delete account
Card -> Service: deleteAccount(accountId)
Service -> Dio: delete /admin/delete-accounts/$accountId
Service <-- Dio: response
Service -> Model: AdminDeleteAccountResponse.fromJson(response)
Service <-- Model: AdminDeleteAccountResponse
Card <-- Service: AdminDeleteAccountResponse
Admin <-- Card: AdminUsersCard
else cancel delete account
Admin -> Card: cancel delete account
Admin <-- Card: AdminUsersCard
end






@enduml