@startuml Admin Logout
' Global param
title Admin Logout
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor Admin
participant "__:AdminUsersPage__" as Page <<view>>
participant "__:AdminService__" as Service
participant "__:Admin__" as Model <<model>>
participant "__:DioInstance__" as Dio


' Sequence diagram
Admin -> Page: build(context)
Admin <-- Page: return confirmation pop up
alt confirm logout
Admin -> Page: confirm logout
Page -> Service: adminLogout()
Service -> Dio: get /admin/logout
Service <-- Dio: response
Service -> Model: AdminLogoutResponse.fromJson(response)
Service <-- Model: AdminLogoutResponse
Page <-- Service: AdminLogoutResponse
Admin <-- Page: AdminLoginPage
else cancel logout
Admin -> Page: cancel logout
Admin <-- Page: AdminUsersPage
end




@enduml