@startuml Login
' Global param
title Login
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "__:LoginPage__" as Page <<view>>
participant "__:AccountService__" as Service
participant "__:Account__" as Model <<model>>
participant "__:DioInstance__" as Dio


' Sequence diagram
User -> Page: build(context)
User <-- Page: LoginPage
User -> Page: LoginForm()
alt Validation is Successful
Page -> Model: RequestLoginModel(email, password)
Page <-- Model: RequestLoginModel
Page -> Service: login(loginReq)
Service -> Dio : post /accounts/login
Service <-- Dio : response
Service -> Model: ResponseLoginModel.fromJson(response)
Service <-- Model: ResponseLoginModel
Page <-- Service: ResponseLoginModel
User <-- Page: AdoptionListPage
else Validation Fails
User <-- Page: show error message
end




@enduml