@startuml Comment Feeds
' Global param
title Comment Feeds
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "__:CommentPage__" as Page <<view>>
participant "__:CommentCard__" as Card <<view>>
participant "__:FeedsService__" as Service
participant "__:Feeds__" as Model <<model>>
participant "__:DioInstance__" as Dio

' Sequence diagram
User -> Page: build(context)
Page -> Service : openCommentSection(feedsId)
Service -> Dio : get /feeds/open-comments/feeds-id/$feedsId
Service <-- Dio : response
Service -> Model : OpenCommentsResponse.fromJson(response)
Service <-- Model : OpenCommentsResponse
Page <-- Service : list<OpenCommentsResponse>
Page -> Card : build(context)
Page <-- Card : CommentCard
User <-- Page: CommentPage


@enduml