@startuml Register
' Global param
title Register
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "_:RegisterPage_" as Page <<view>>
participant "_:AccountService_" as Service
participant "_:Account" as Model <<model>>


' Sequence diagram
User -> Page: build
User <-- Page: return RegisterPage
User -> Page: build
alt Validation is Successful
Page -> Model: RequestRegisterModel req
Page <-- Model: return RequestRegisterModel
Page -> Service: register(registerReq)
Service -> Model: RequestRegisterModel registerReq
Service <-- Model: return ResponseRegisterModel
Page <-- Service: return ResponseRegisterModel
User <-- Page: return LoginPage
else Validation Fails
    User <-- Page: return ErrorMessage
end


@enduml