@startuml Login
' Global param
title Login
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "_:LoginPage_" as Page <<view>>
participant "_:AccountService_" as Service
participant "_:Account_" as Model <<model>>
participant "_:DioInstance_" as Dio


' Sequence diagram
User -> Page: build(context)
User <-- Page: LoginPage
User -> Page: LoginForm()
alt Validation is Successful
Page -> Model: RequestLoginModel(email, password)
Page <-- Model: RequestLoginModel
Page -> Service: login(loginReq)
Service -> Dio : post /accounts/login
Service <-- Dio : response
Service -> Model: ResponseLoginModel.fromJson(response)
Service <-- Model: ResponseLoginModel
Page <-- Service: ResponseLoginModel
User <-- Page: AdoptionListPage
else Validation Fails
    User <-- Page: show error message
end




@enduml