@startuml Logout
' Global param
title Logout
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor "Adopter / Dog Owner" as User
participant "__:UserProfilePage__" as Page <<view>>
participant "__:AccountService__" as Service
participant "__:DioInstance__" as Dio
participant "__:Account__" as Model <<model>>



' Sequence diagram
User -> Page: build(context)
User <-- Page: return confirmation pop up
alt confirm logout
User -> Page: confirm logout
Page -> Service: logout()
Service -> Dio: get /accounts/logout
Service <-- Dio: response
Service -> Model: LogoutResponse.fromJson(response)
Service <-- Model: LogoutResponse
Page <-- Service: LogoutResponse
User <-- Page: LoginPage
else cancel logout
User -> Page: cancel logout
User <-- Page: UserProfilePage
end




@enduml