@startuml View User Profile
' Global param
title View User Profile
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "_:UserProfilePage_" as Page <<view>>
participant "_:AccountService_" as Service
participant "_:Account" as Model <<model>>
participant "_:ImageNetwork_" as Image
participant "_:DioInstance_" as Dio

' Sequence diagram
User -> Page: build(context)
Page -> Service : retrieveUserData()
Service -> Dio : get /accounts/login
Service <-- Dio : response
Service -> Model : ResponseUserProfileModel.fromJson
Service <-- Model : ResponseUserProfileModel
Page <-- Service : ResponseUserProfileModel
Page -> Image : ImageNetwork(urlImage, width, height)
Page <-- Image : image
User <-- Page: UserProfilePage


@enduml