@startuml View User Profile
' Global param
title View User Profile
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "__:UserProfilePage__" as Page <<view>>
participant "__:AccountService__" as Service
participant "__:Account__" as Model <<model>>
participant "__:ImageNetwork__" as Image
participant "__:DioInstance__" as Dio

' Sequence diagram
User -> Page: build(context)
Page -> Service : retrieveUserData()
Service -> Dio : get /accounts/login
Service <-- Dio : response
Service -> Model : ResponseUserProfileModel.fromJson(response)
Service <-- Model : ResponseUserProfileModel
Page <-- Service : ResponseUserProfileModel
Page -> Image : ImageNetwork(urlImage, width, height)
Page <-- Image : image
User <-- Page: UserProfilePage


@enduml