@startuml View Adoption Confirmation Page
' Global param
title View Adoption Confirmation Page
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor "Adopter" as User
participant "__: RequestAdoptionPage__" as Page <<view>>
participant "__:AdoptionService__" as Service
participant "__:Adoption__" as Model <<model>>
participant "__:DioInstance__" as Dio
participant "__:ImageNetwork__" as Image


' Sequence diagram
User -> Page: build(context)
Page -> Service: retrieveAdoptConfirmation(dogId)
Service -> Dio : get /adoption/confirmation/dog-id/$dogId
Service <-- Dio : response
Service -> Model : AdoptConfirmationRequest.fromJson(response)
Service <-- Model : AdoptConfirmationRequest
Page <-- Service : AdoptConfirmationRequest
Page -> Image : ImageNetwork(urlImage, width, height)
Page <-- Image : image
User <-- Page: RequestAdoptionPage

@enduml