@startuml RequestToAdopt
' Global param
title  Request To Adopt
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "_: RequestForAdoption_" as  Page <<view>>
participant "_:AdoptionService_" as Service
participant "_:_Adoption_" as Model <<model>>
participant "_:DioInstance_" as Dio


' Sequence diagram
User -> Page: build(context)
User <-- Page: return confirmation pop up
alt confirm request adoption
User -> Page: confirm request adoption
Page -> Model: sendAdoptNotif(dogId, dogName, breedName, ownerId, ownerUsername)
Page <-- Model: SendAdoptionNotification
Page -> Service: sendAdoptNotif(adopt)
Service -> Dio: post /adoption/send-notification
Service <-- Dio: response
Service -> Model: SendAdoptionNotification.fromJson(response)
Service <-- Model: SendAdoptionNotification
Page <-- Service: SendAdoptionNotification
User <-- Page: ChatroomPage
else cancel request adoption
User -> Page: cancel request adoption
User <-- Page: RequestAdoptionPage
end

@enduml