@startuml Request For Dog Adoption
' Global param
title  Request For Dog Adoption
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor "Adopter" as User
participant "__: RequestAdoptionPage__" as  Page <<view>>
participant "__:AdoptionService__" as Service
participant "__:_Adoption__" as Model <<model>>
participant "__:DioInstance__" as Dio


' Sequence diagram
User -> Page: reqAdoptDetail()
User <-- Page: return confirmation pop up
alt confirm request adoption
User -> Page: confirm request adoption
Page -> Model: SendAdoptionNotification(dogId, dogName, breedName, ownerId, ownerUsername)
Page <-- Model: SendAdoptionNotification
Page -> Service: sendAdoptNotif(adopt)
Service -> Dio: post /adoption/send-notification
Service <-- Dio: response
Service -> Model: SendAdoptionNotification.fromJson(response)
Service <-- Model: SendAdoptionNotification
Page <-- Service: SendAdoptionNotification
User <-- Page: ChatroomPage
else cancel request adoption
User -> Page: cancel request adoption
User <-- Page: RequestAdoptionPage
end

@enduml