@startuml ViewAdoptionPage
' Global param
title View Adoption Page
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "__:AdoptionPage__" as Page <<view>>
participant "__:AdoptionCardDetail__" as Card <<view>>
participant "__:ProvinceService__" as ServiceProvince
participant "__:DogService__" as ServiceDog
participant "__:AdoptionService__" as ServiceAdoption
participant "__:Province__" as ModelProvince <<model>>
participant "__:Dog__" as ModelDog <<model>>
participant "__:Adoption__" as ModelAdoption <<model>>
participant "__:DioInstance__" as Dio


' Sequence diagram
User -> Page: build(context)
Page -> ServiceProvince : retrieveAllProvince()
ServiceProvince -> Dio : get /provinces/all
ServiceProvince <-- Dio : response
ServiceProvince -> ModelProvince : RetrieveAllProvinceResponse.fromJson(response)
ServiceProvince <-- ModelProvince : RetrieveAllProvinceResponse
Page <-- ServiceProvince : RetrieveAllProvinceResponse
Page -> ServiceDog : retrieveAllBreed()
ServiceDog -> Dio : get /breeds/all
ServiceDog <-- Dio : response
ServiceDog -> ModelDog : RetrieveAllBreedResponse.fromJson(response)
ServiceDog <-- ModelDog : RetrieveAllBreedResponse
Page <-- ServiceDog : RetrieveAllBreedResponse
Page -> ServiceAdoption : retrieveAdoptionList(filterAdoption)
ServiceAdoption -> Dio : get /adoption/view
ServiceAdoption <-- Dio : response
ServiceAdoption -> ModelAdoption : AdoptionDetail.fromJson(response)
ServiceAdoption <-- ModelAdoption : AdoptionDetail
Page <-- ServiceAdoption : list<AdoptionDetail>
Page -> Card : build(context)
Page <-- Card : AdoptionCardDetail
User <-- Page: AdoptionListPage


@enduml