@startuml AddDog
' Global param
title Add Dog
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "__:AddDogPage__" as Page <<view>>
participant "__:ImageService__" as ServiceImage
participant "__:DogService__" as ServiceDog
participant "__:Image__" as ModelImage <<model>>
participant "__:Dog__" as ModelDog <<model>>
participant "__:ImageNetwork__" as Image
participant "__:DioInstance__" as Dio


' Sequence diagram
User -> Page: build(context)
User <-- Page: AddDogPage
User -> Page: AddDogProfile()
Page -> ServiceImage : uploadDogImage(dogId, image)
ServiceImage -> Dio : post /upload/dog
ServiceImage <-- Dio : response
ServiceImage -> ModelImage : UploadImageResponse.fromJson(response)
ServiceImage <-- ModelImage : UploadImageResponse
Page <-- ServiceImage : UploadImageResponse
Page -> Image : ImageNetwork(urlImage, width, height)
Page <-- Image : image
alt Validation is Successful
Page -> ModelDog: AddDogRequest(dogName, breedName, gender, provinceName, vaccination, description, dateOfBirth, isAdoption, image)
Page <-- ModelDog: AddDogRequest
Page -> ServiceDog: addNewDog(request)
ServiceDog -> Dio : post /dogs/add
ServiceDog <-- Dio : response
ServiceDog -> ModelDog: AddDogResponse.fromJson(response)
ServiceDog <-- ModelDog: AddDogResponse
Page <-- ServiceDog: AddDogResponse
User <-- Page: DogListPage
else Validation Fails
User <-- Page: show error message
end




@enduml