@startuml Delete Dog
' Global param
title Delete Dog
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor "Dog Owner" as User
participant "__: MyDogCard__" as Card <<view>>
participant "__:DogService__" as Service
participant "__:Dog__" as Model <<model>>
participant "__:DioInstance__" as Dio


' Sequence diagram
User -> Card: build(context)
User <-- Card: return confirmation pop up
alt confirm delete dog
User -> Card: confirm delete dog
Card -> Service: deleteDog(dogId)
Service -> Dio: delete /dogs/delete/dog-id/$dogId
Service <-- Dio: response
Service -> Model: DeleteDogResponse.fromJson(response)
Service <-- Model: DeleteDogResponse
Card <-- Service: DeleteDogResponse
User <-- Card: DogListPage
else cancel delete dog
User -> Card: cancel delete dog
User <-- Card: DogListPage
end

@enduml