@startuml DeleteDod
' Global param
title Delete Dog
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor User
participant "_: MyDogCard_" as Card <<view>>
participant "_:DogService_" as Service
participant "_:Dog_" as Model <<model>>
participant "_:ImageNetwork_" as Image
participant "_:DioInstance_" as Dio


' Sequence diagram
User -> Card: build(context)
User <-- Card: return confirmation pop up
alt delete dog
User -> Card: confirm delete dog
Card -> Service: deleteDog(dogId)
Service -> Dio: /dogs/delete/dog-id/$dogId
Service <-- Dio: response
Service -> Model: DeleteDogResponse.fromJson(response)
Service <-- Model: DeleteDogResponse
Card <-- Service: DeleteDogResponse
User <-- Card: DogListPage
else cancel delete dog
User -> Card: cancel delete dog
User <-- Card: DogListPage
end

@enduml