@startuml View Other Dog Profile Page
' Global param
title View Other Dog Profile Page
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor "Adopter / Dog Owner" as User
participant "__:OtherDogProfilePage__" as Page <<view>>
participant "__:DogService__" as Service
participant "__:Dog__" as Model <<model>>
participant "__:ImageNetwork__" as Image
participant "__:DioInstance__" as Dio

' Sequence diagram
User -> Page: build(context)
Page -> Service : retrieveDogProfile(dogId)
Service -> Dio : get /dogs/profile/dog-id/$dogId
Service <-- Dio : response
Service -> Model : ResponseDogProfileModel.fromJson(response)
Service <-- Model : ResponseDogProfileModel
Page <-- Service : ResponseDogProfileModel
Page -> Image : ImageNetwork(urlImage, width, height)
Page <-- Image : image
User <-- Page: OtherDogProfilePage


@enduml