@startuml View Other Dog List Page
' Global param
title View Other Dog List Page
autoactivate on

' Global style configuration
skinparam RoundCorner 0
hide footbox

' Sequence participant configuration
actor "Adopter / Dog Owner" as User
participant "__:OtherDogListPage__" as Page <<view>>
participant "__:MyDogCard__" as Card <<view>>
participant "__:DogService__" as Service
participant "__:Dog__" as Model <<model>>
participant "__:DioInstance__" as Dio
participant "__:ImageNetwork__" as Image


' Sequence diagram
User -> Page: build(context)
Page -> Service : retrieveDogList(accountId)
Service -> Dio : get /account-dog/account-id/$accountId
Service <-- Dio : response
Service -> Model : ResponseDogCard.fromJson(response)
Service <-- Model : ResponseDogCard
Page <-- Service : List<ResponseDogCard>
Page -> Card : build(context)
Card -> Model : ResponseDogCard
Card <-- Model : ResponseDogCard
Card -> Image : ImageNetwork(urlImage, width, height)
Card <-- Image : image
Page <-- Card : OtherDogCard
User <-- Page: OtherDogListPage


@enduml